modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"

[[mods]]
modId="arlightweaponskins"
version="${version}"
displayName="Arlight Weapon Skins"
authors="Arlight"
description='''
Skins 3D de GeckoLib administradas mediante seis ranuras visibles de Curios.
'''
displayTest="IGNORE_SERVER_VERSION"

[[mixins]]
config="arlightweaponskins.mixins.json"

[[dependencies.arlightweaponskins]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="CLIENT"

[[dependencies.arlightweaponskins]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="CLIENT"

[[dependencies.arlightweaponskins]]
modId="geckolib"
type="required"
versionRange="[4.9,)"
ordering="AFTER"
side="CLIENT"

[[dependencies.arlightweaponskins]]
modId="arlightchatclient"
type="required"
versionRange="[5.3.0,)"
ordering="AFTER"
side="CLIENT"

[[dependencies.arlightweaponskins]]
modId="arlightcosmeticscurios"
type="required"
versionRange="[1.17.0,)"
ordering="AFTER"
side="BOTH"
